//! `extern "C"` API for zimru. Built only when the `cffi` Cargo feature is
//! enabled.
//!
//! All public types in this module use C-style snake_case names
//! (`zimru_archive_t` etc.) intentionally, so the cbindgen-generated header
//! is consistent with the function names. Rust's normal CamelCase
//! convention does not apply to FFI surfaces.

#![allow(non_camel_case_types)]
// Per-fn safety docs would be redundant with the module preamble above:
// every `unsafe extern "C" fn` here follows the same conventions
// (string lifetimes, error-out-pointer protocol, ownership rules).
#![allow(clippy::missing_safety_doc)]
//!
//! See `include/zimru.h` (generated by cbindgen at build time) for the
//! C-side declarations of every symbol exposed here. Conventions:
//!
//! * **Strings** — every returned `*const c_char` is NUL-terminated and
//!   remains valid for as long as the parent handle (Entry / Item /
//!   Archive) is alive. Callers that need a longer lifetime must copy.
//! * **Bytes** — returned via pointer + length; not NUL-terminated.
//!   Lifetime is tied to the parent handle.
//! * **Errors** — every fallible function takes a `*mut *mut zimru_error_t`
//!   out-parameter. On success the out-parameter is left untouched. On
//!   failure the function returns NULL / 0 / false *and* writes a
//!   heap-allocated error pointer; the caller frees it with
//!   [`zimru_error_free`].
//! * **Ownership** — anything returned through an `*mut zimru_*_t` pointer
//!   is owned by the caller and must be freed with the matching
//!   `zimru_*_free` function.
//!
//! The Rust API in [`crate::archive`] is unchanged; this module is purely
//! an additional surface.

mod archive;
mod blob;
mod creator;
mod entry;
mod error;
mod item;
mod uuid;

pub use archive::*;
pub use blob::*;
pub use creator::*;
pub use entry::*;
pub use error::*;
pub use item::*;
pub use uuid::*;
