#![cfg(all(feature = "cffi", feature = "writer"))]
//! Drives `tests/cffi_smoke.c` end-to-end:
//!
//! 1. Build a tiny ZIM via `zimru::writer::Creator` (one HTML article
//!    "home" containing the marker "ZIMRU-OK").
//! 2. Compile `tests/cffi_smoke.c` against `include/zimru.h` and link
//!    against the just-built `libzimru.so` / `libzimru.dylib`.
//! 3. Run the resulting binary with the ZIM path as argv[1].
//! 4. Assert exit 0.
//!
//! Skipped silently if a C compiler isn't available on PATH.

use std::path::{Path, PathBuf};
use std::process::Command;

use zimru::writer::{Creator, Item};
use zimru::Compression;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn target_dir() -> PathBuf {
    // tests run from CARGO_MANIFEST_DIR; release artefacts under target/release.
    manifest_dir().join("target").join("release")
}

fn cc() -> Option<&'static str> {
    ["cc", "gcc", "clang"]
        .into_iter()
        .find(|c| Command::new(c).arg("--version").output().is_ok())
}

fn build_test_zim(out: &Path) {
    let mut c = Creator::new();
    c.set_compression(Compression::Zstd);
    c.set_main_path("home");
    c.add_item(Item::html(
        "home",
        "Home Page",
        "<!doctype html><html><body>ZIMRU-OK marker for the C smoke test.</body></html>",
    ));
    c.add_metadata("Title", "cffi smoke test");
    c.add_metadata("Language", "eng");
    c.write_to(out).expect("write test zim");
}

#[test]
fn c_consumer_can_read_a_zim_via_the_c_abi() {
    let Some(cc) = cc() else {
        eprintln!("skip: no C compiler on PATH");
        return;
    };

    // 1) Build the ZIM.
    let zim = std::env::temp_dir().join(format!(
        "zimru-cffi-smoke-{}-{}.zim",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos(),
    ));
    build_test_zim(&zim);

    // 2) Compile the C harness. We need:
    //    - libzimru built with the cffi feature (a .so/.dylib in target/release)
    //    - include/zimru.h (generated by build.rs)
    //    The Rust harness only runs in `cargo test --features cffi`, so
    //    cargo will already have ensured libzimru is up-to-date for the
    //    same feature set.
    let lib_dir = target_dir();
    let header_dir = manifest_dir().join("include");
    if !header_dir.join("zimru.h").exists() {
        panic!("include/zimru.h missing — did `cargo build --features cffi` run?");
    }
    // Locate the built dylib. Linux: libzimru.so. Mac: libzimru.dylib.
    let dylib_name = if cfg!(target_os = "macos") {
        "libzimru.dylib"
    } else if cfg!(target_os = "windows") {
        "zimru.dll"
    } else {
        "libzimru.so"
    };
    let dylib_path = lib_dir.join(dylib_name);
    assert!(
        dylib_path.exists(),
        "{} not found — build with --features cffi first",
        dylib_path.display()
    );

    let c_src = manifest_dir().join("tests").join("cffi_smoke.c");
    let bin = std::env::temp_dir().join(format!("zimru_cffi_smoke_{}", std::process::id()));

    // Compile + link in one go.
    let rpath_arg = format!("-Wl,-rpath,{}", lib_dir.display());
    let mut cmd = Command::new(cc);
    cmd.arg("-std=c11")
        .arg("-D_GNU_SOURCE") // memmem on glibc
        .arg("-I")
        .arg(&header_dir)
        .arg("-L")
        .arg(&lib_dir)
        .arg(&rpath_arg)
        .arg(&c_src)
        .arg("-lzimru")
        .arg("-o")
        .arg(&bin);
    let status = cmd.status().expect("invoke cc");
    assert!(status.success(), "cc failed");

    // 3) Run.
    let out = Command::new(&bin)
        .arg(&zim)
        .env("LD_LIBRARY_PATH", &lib_dir)
        .env("DYLD_LIBRARY_PATH", &lib_dir)
        .output()
        .expect("run cffi_smoke binary");
    eprintln!(
        "--- cffi_smoke stderr ---\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    eprintln!(
        "--- cffi_smoke stdout ---\n{}",
        String::from_utf8_lossy(&out.stdout)
    );
    assert!(
        out.status.success(),
        "cffi_smoke exited non-zero: {:?}",
        out.status
    );

    // Cleanup.
    let _ = std::fs::remove_file(&zim);
    let _ = std::fs::remove_file(&bin);
}
