/*
 * zimru — independent Rust re-implementation of the ZIM file format.
 *
 * This header is auto-generated by cbindgen from src/cffi/. Do not edit by
 * hand. Regenerate with: cargo build --release --features cffi
 *
 * Strings: returned `const char*` are NUL-terminated and remain valid until
 *   the parent handle (Entry, Item, Archive) is freed. Caller copies if a
 *   longer lifetime is needed.
 * Bytes:   returned via pointer + length; not NUL-terminated. Lifetime tied
 *   to the parent handle.
 * Errors:  fallible functions take a `zimru_error_t** err` out-parameter.
 *   On success *err is left untouched. On failure the function returns NULL
 *   (or 0/false) AND sets *err to a heap-allocated error the caller frees
 *   with zimru_error_free.
 * Ownership: anything returned via `*_t*` is owned by the caller and must
 *   be freed with the matching `*_free` function.
 */


#ifndef ZIMRU_H
#define ZIMRU_H

#pragma once

/* Generated with cbindgen:0.27.0 */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Default content namespace for "new namespace" archives.
 */
#define NS_CONTENT_NEW 67

/**
 * Metadata namespace (new-style archives).
 */
#define NS_METADATA 77

/**
 * Well-known namespace (new-style archives).
 */
#define NS_WELLKNOWN 87

/**
 * Index namespace (search indexes etc.).
 */
#define NS_INDEX 88

/**
 * Articles namespace (legacy archives).
 */
#define NS_ARTICLES_LEGACY 65

/**
 * Default cluster-cache byte budget (sum of decompressed payload bytes
 * held resident at most). Sized for phone-class hosts: 64 MB is enough
 * to keep ~30 typical 2 MB clusters cached for hot-article reuse, but
 * won't dominate a 4 GB-RAM device. Override per-archive with
 * [`Archive::set_cluster_cache_max_bytes`] — bulk-iteration tools that
 * pass over the whole archive once can size up; memory-constrained
 * embedded callers can size down.
 */
#define DEFAULT_CLUSTER_CACHE_MAX_BYTES ((64 * 1024) * 1024)

/**
 * Decompressed-size ceiling for standard (u32 blob offsets) clusters.
 * The format cannot address payload bytes past `u32::MAX` with 4-byte
 * offsets, so anything larger is corrupt input or a decompression bomb.
 */
#define MAX_STANDARD_CLUSTER_BYTES (uint64_t)UINT32_MAX

/**
 * Decompressed-size ceiling for extended (u64 blob offsets) clusters —
 * a defensive bound so a crafted cluster in an untrusted archive cannot
 * grow the decode buffer without limit and OOM the process. 16 GiB,
 * spelled as a decimal literal so the cbindgen-exported C macro stays a
 * well-defined `long long` constant (a `16 << 30` would overflow `int`).
 */
#define MAX_EXTENDED_CLUSTER_BYTES 17179869184

#define MIME_REDIRECT 65535

#define MIME_LINKTARGET 65534

#define MIME_DELETED 65533

#define MAGIC 72173914

#define HEADER_SIZE 80

#define NO_MAIN_PAGE UINT32_MAX

/**
 * Default target size for one cluster's worth of decompressed payload
 * (2 MiB — same as libzim's zimwriterfs default).
 */
#define DEFAULT_CLUSTER_SIZE_TARGET ((2 * 1024) * 1024)

/**
 * Default zstd compression level when the caller pins none and no
 * `ZSTD_CLEVEL` env override is set. Level 19 is the high-ratio
 * default we benchmark against libzim (still ~1.5× faster than
 * libzim at the same level); callers wanting fast-but-large output
 * can drop it via [`Creator::set_compression_level`] or `ZSTD_CLEVEL`.
 */
#define DEFAULT_ZSTD_LEVEL 19

/**
 * Opaque handle wrapping a [`crate::Archive`] plus the caches used to
 * give C callers stable pointers.
 */
typedef struct zimru_archive_t zimru_archive_t;

/**
 * Opaque blob handle wrapping a [`crate::Blob`]. Holds the underlying
 * `Arc<[u8]>` cluster slice alive so the borrowed pointer returned by
 * `zimru_blob_data` stays valid until the blob is freed.
 */
typedef struct zimru_blob_t zimru_blob_t;

/**
 * Opaque writer handle. Owns a [`Creator`] until `zimru_creator_write_to`
 * consumes it. The chunked-item in-flight state lives on the underlying
 * `Creator`'s streamer (so the streaming-encode variant can take the
 * output file out from under the writer mid-item without aliasing).
 */
typedef struct zimru_creator_t zimru_creator_t;

/**
 * Opaque entry handle. Holds a Rust `Entry` plus owned `CString`s for
 * `path` and `title` so the C-side `const char*` returned by
 * `zimru_entry_path` / `zimru_entry_title` are stable for the entry's
 * lifetime.
 */
typedef struct zimru_entry_t zimru_entry_t;

/**
 * Opaque error type returned by every fallible C API entry point.
 * Intentionally NOT `#[repr(C)]` so cbindgen forward-declares it as an
 * opaque struct in the generated header (callers can only hold a
 * `zimru_error_t*`, never inspect the layout).
 */
typedef struct zimru_error_t zimru_error_t;

/**
 * Opaque item handle. Holds a Rust `Item` plus owned `CString`s for
 * `path` and `mimetype` so the C-side `const char*` returned by the
 * accessors stays valid for the item's lifetime.
 */
typedef struct zimru_item_t zimru_item_t;

/**
 * Snapshot of cluster-cache occupancy and lifetime counters. Mirrors
 * [`crate::ClusterCacheStats`]. Counters are monotonic over the
 * archive's lifetime — useful for verifying hot-article hit ratios,
 * tuning the byte budget against eviction pressure, or surfacing
 * cache health to long-running-server telemetry.
 */
typedef struct zimru_cluster_cache_stats_t {
  uint64_t max_bytes;
  uint64_t current_bytes;
  uint64_t entries;
  uint64_t hits;
  uint64_t misses;
  uint64_t evictions;
} zimru_cluster_cache_stats_t;

/**
 * Cover / thumbnail descriptor returned by
 * [`zimru_archive_illustrations`]. Mirrors libzim's
 * `IllustrationInfo`: width and height in pixels, and a `scale`
 * factor (typically 1 or 2 for HiDPI variants).
 */
typedef struct zimru_illustration_t {
  uint32_t width;
  uint32_t height;
  uint32_t scale;
} zimru_illustration_t;

/**
 * Direct-access info for an item. POD struct populated by
 * [`zimru_item_direct_access`]; mirrors [`crate::DirectAccess`].
 *
 * When `is_direct` is `true`, callers can `pread()` or `mmap()` the
 * item's bytes directly from the on-disk ZIM file at `file_offset`
 * for `size` bytes — no decompression, no copy. The standard ZIM
 * convention is to store fulltext / suggestion / Xapian indexes in
 * uncompressed clusters precisely so consumers can hand `libxapian`
 * an `int fd` + `lseek` instead of materialising the database in
 * memory or in a temp file.
 *
 * When `is_direct` is `false`, the item lives in a compressed
 * cluster; fall back to [`zimru_item_get_data`] for normal access.
 */
typedef struct zimru_direct_access_t {
  bool is_direct;
  uint64_t file_offset;
  uint64_t size;
} zimru_direct_access_t;

/**
 * Zero-allocation blob view: a borrowed `(data, size)` slice into the
 * item's decompressed cluster, plus an opaque pin handle that keeps
 * the underlying cluster alive even if the LRU cluster cache evicts
 * the entry. Designed for hot-path consumers (servers serving content
 * per-request) that would otherwise pay one heap allocation per call
 * for the `zimru_blob_t*` wrapper.
 *
 * Populated by [`zimru_item_blob_view`]; released by
 * [`zimru_blob_view_release`]. Treat `_pin` as opaque — it is not a
 * data pointer.
 */
typedef struct zimru_blob_view_t {
  const uint8_t *data;
  uint64_t size;
  /**
   * Opaque cluster-pin handle. Pass to
   * [`zimru_blob_view_release`]; do not dereference. NULL means the
   * view has already been released (or was never populated).
   */
  const void *_pin;
} zimru_blob_view_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open the archive at `path` (UTF-8, NUL-terminated). Returns NULL on
 * failure and sets `*err`.
 */
 struct zimru_archive_t *zimru_archive_open(const char *path, struct zimru_error_t **err);

/**
 * Close and free a `zimru_archive_t` previously returned by
 * `zimru_archive_open`.
 */
 void zimru_archive_close(struct zimru_archive_t *arc);

/**
 * Total number of dirents (articles + redirects).
 */
 uint32_t zimru_archive_entry_count(const struct zimru_archive_t *arc);

/**
 * Same as `zimru_archive_entry_count`, included for parity with libzim's
 * `getAllEntryCount`.
 */
 uint32_t zimru_archive_all_entry_count(const struct zimru_archive_t *arc);

/**
 * Number of clusters in the archive.
 */
 uint32_t zimru_archive_cluster_count(const struct zimru_archive_t *arc);

/**
 * Copy the archive's 16-byte UUID into `out`. `out` must point to at
 * least 16 writable bytes.
 */
 void zimru_archive_uuid(const struct zimru_archive_t *arc, uint8_t *out);

/**
 * True iff the archive has a main entry pointer in its header.
 */
 bool zimru_archive_has_main_entry(const struct zimru_archive_t *arc);

/**
 * True iff the archive carries a trailing MD5 checksum.
 */
 bool zimru_archive_has_checksum(const struct zimru_archive_t *arc);

/**
 * Verify the trailing MD5 checksum. Returns true on match, false on
 * mismatch, and false-with-`*err`-set on failure to even compute it.
 */
 bool zimru_archive_check(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Look up an entry by its full namespaced path (e.g. `"C/index.html"`).
 * Returns NULL with `*err` set if not found.
 */

struct zimru_entry_t *zimru_archive_get_entry_by_path(const struct zimru_archive_t *arc,
                                                      const char *path,
                                                      struct zimru_error_t **err);

/**
 * True iff an entry with this path exists. Equivalent to
 * `zimru_archive_get_entry_by_path` returning non-NULL, without the
 * allocation.
 */
 bool zimru_archive_has_entry_by_path(const struct zimru_archive_t *arc, const char *path);

/**
 * Look up an entry by namespace + URL within that namespace
 * (e.g. ns=`'X'`, url=`"fulltext/xapian"`). This is the primitive
 * downstream callers need to reach the X / M / W namespaces on
 * new-scheme archives — `zimru_archive_get_entry_by_path` only looks
 * in the content namespace by design.
 *
 * Returns NULL with `*err` set if not found.
 */

struct zimru_entry_t *zimru_archive_get_entry_by_ns_path(const struct zimru_archive_t *arc,
                                                         uint8_t ns,
                                                         const char *url,
                                                         struct zimru_error_t **err);

/**
 * Look up an entry by its URL-pointer index (path order). Index range
 * is `[0, all_entry_count)`.
 */

struct zimru_entry_t *zimru_archive_entry_by_url_index(const struct zimru_archive_t *arc,
                                                       uint32_t idx,
                                                       struct zimru_error_t **err);

/**
 * Look up an entry by its title-pointer index (title order). On modern
 * archives this only covers the content namespace; index range is
 * `[0, zimru_archive_title_count)`.
 */

struct zimru_entry_t *zimru_archive_entry_by_title_index(const struct zimru_archive_t *arc,
                                                         uint32_t idx,
                                                         struct zimru_error_t **err);

/**
 * Number of entries in the title-order listing. On modern archives
 * this is the count of content-namespace entries only.
 */
 uint32_t zimru_archive_title_count(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Look up an entry by title in the content namespace. Returns NULL
 * with `*err` set if not found.
 */

struct zimru_entry_t *zimru_archive_get_entry_by_title(const struct zimru_archive_t *arc,
                                                       const char *title,
                                                       struct zimru_error_t **err);

/**
 * True iff this archive uses the modern single-character namespace
 * scheme (content under `C/`, metadata under `M/`, indexes under
 * `X/`, well-known under `W/`). Old archives put articles in `A/`.
 */
 bool zimru_archive_uses_new_namespaces(const struct zimru_archive_t *arc);

/**
 * True iff the archive was opened from a split `.zimaa`/`.zimab`/...
 * part-set rather than a single `.zim` file. zimru does not yet
 * implement multipart open, so this currently always returns `false`;
 * the accessor exists so downstream tooling that branches on it
 * (single- vs multi-URL download flows) can compile and run against
 * zimru without conditionally compiling the call out.
 */
 bool zimru_archive_is_multipart(const struct zimru_archive_t *arc);

/**
 * Reconfigure the cluster-cache byte budget. The cache holds
 * decompressed clusters; `max_bytes` caps the summed payload sizes
 * resident at once. The default is conservative (~64 MB) so memory-
 * constrained hosts (phones, embedded) don't pin hundreds of MB of
 * decompressed cluster data; bulk-iteration tools can size up.
 */

void zimru_archive_set_cluster_cache_max_bytes(const struct zimru_archive_t *arc,
                                               uintptr_t max_bytes);

/**
 * Current cluster-cache byte budget. Returns `0` on a NULL archive.
 */
 uintptr_t zimru_archive_cluster_cache_max_bytes(const struct zimru_archive_t *arc);

/**
 * Populate `out` with the cluster cache's current state. Safe on a
 * NULL `arc` or `out` (no-op).
 */

void zimru_archive_cluster_cache_stats(const struct zimru_archive_t *arc,
                                       struct zimru_cluster_cache_stats_t *out);

/**
 * Enumerate every illustration descriptor recorded in the archive's
 * metadata. ZIM stores covers/thumbnails as
 * `M/Illustration_<W>x<H>@<scale>` entries; this returns a heap-
 * allocated array sorted ascending. Sets `*out_count` and returns the
 * pointer; the caller frees with [`zimru_illustrations_free`]. On
 * archives with no illustrations sets `*out_count = 0` and returns
 * NULL (still safe to pass to free).
 */

struct zimru_illustration_t *zimru_archive_illustrations(const struct zimru_archive_t *arc,
                                                         uintptr_t *out_count);

/**
 * Free an illustration array previously returned by
 * [`zimru_archive_illustrations`]. `count` must match the value
 * written into `*out_count`. Safe on a NULL pointer (no-op).
 */
 void zimru_illustrations_free(struct zimru_illustration_t *ptr, uintptr_t count);

/**
 * Half-open title-order range `[*out_lo, *out_hi)` of entries in
 * namespace `ns` whose title starts with `prefix`. Returns `true` on
 * success (including empty matches, where `*out_lo == *out_hi`),
 * `false` with `*err` set on a parse failure. `prefix` is a
 * NUL-terminated UTF-8 string. Designed to back
 * `SuggestionSearcher` fallbacks; iterate the returned range and
 * resolve each index with `zimru_archive_entry_by_title_index`.
 */

bool zimru_archive_title_prefix_range(const struct zimru_archive_t *arc,
                                      uint8_t ns,
                                      const char *prefix,
                                      uint32_t *out_lo,
                                      uint32_t *out_hi,
                                      struct zimru_error_t **err);

/**
 * Write the archive's trailing-MD5 checksum into `out` as a 32-byte
 * lowercase hex string (no NUL terminator, no hyphens). Returns
 * `false` with `*err` set if the archive has no checksum or the read
 * fails. `out` must point to at least 32 writable bytes.
 */

bool zimru_archive_checksum_hex(const struct zimru_archive_t *arc,
                                char *out,
                                struct zimru_error_t **err);

/**
 * Look up the archive's main entry. Returns NULL with `*err` set if the
 * archive has no main page.
 */

struct zimru_entry_t *zimru_archive_main_entry(const struct zimru_archive_t *arc,
                                               struct zimru_error_t **err);

/**
 * URL-pointer index of the archive's main entry, or
 * [`NO_MAIN_PAGE`] (`0xFFFFFFFF`) when no main entry is set in the
 * header. Cheaper than [`zimru_archive_main_entry`] — avoids the
 * dirent parse and the entry-handle allocation — for callers that
 * only need the index (e.g. the libzim-shim's `getMainEntryIndex()`,
 * or zim-tools' equality checks against `entry.index()` while
 * iterating).
 */
 uint32_t zimru_archive_main_entry_index(const struct zimru_archive_t *arc);

/**
 * Absolute on-disk byte offset of cluster `idx` (the byte where the
 * cluster's leading info-byte begins). Used by `zimsplit` /
 * `zimdump` to walk the cluster region by file position. Returns
 * `0` with `*err` set on out-of-range indices or read errors.
 */

uint64_t zimru_archive_cluster_offset(const struct zimru_archive_t *arc,
                                      uint32_t idx,
                                      struct zimru_error_t **err);

/**
 * Verify every URL-pointer-list entry resolves to a parseable dirent
 * within file bounds. Returns `true` on a clean archive, `false` on a
 * structural defect, `false` with `*err` set if the pointer list
 * itself can't be read. Designed as one of the per-check primitives
 * the libzim-shim's `IntegrityCheckList` / `validate()` aggregator
 * composes; callers that want a single yes/no can `&&` the set.
 */

bool zimru_archive_check_dirent_ptrs(const struct zimru_archive_t *arc,
                                     struct zimru_error_t **err);

/**
 * Verify every dirent appears in `(namespace, url)` order in the
 * URL-pointer list. A `false` here would silently break every path
 * lookup on the archive (the binary search returns the wrong leaf or
 * `EntryNotFound`).
 */

bool zimru_archive_check_dirent_order(const struct zimru_archive_t *arc,
                                      struct zimru_error_t **err);

/**
 * Verify the title-pointer list (legacy archives) or the modern
 * `X/listing/titleOrdered/v1` stream yields dirents in
 * `(namespace, title)` order. `entry_by_ns_title` is a binary search
 * over this ordering.
 */

bool zimru_archive_check_title_index(const struct zimru_archive_t *arc,
                                     struct zimru_error_t **err);

/**
 * Verify every cluster-pointer-list entry is in-bounds for the file.
 * Catches truncation between the end of the dirent region and the
 * trailing checksum.
 */

bool zimru_archive_check_cluster_ptrs(const struct zimru_archive_t *arc,
                                      struct zimru_error_t **err);

/**
 * Verify every article-dirent's mimetype index resolves inside the
 * on-file mime-type list. Reserved values `0xFFFE` (linktarget) and
 * `0xFFFD` (deletedentry) are accepted as legal even though they sit
 * outside the list.
 */
 bool zimru_archive_check_mimetypes(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Read a metadata value as raw bytes. Writes the byte count to `out_len`
 * and returns a borrowed pointer (lifetime tied to `arc`).
 *
 * Returns NULL with `*err` set if the metadata key isn't present.
 */

const uint8_t *zimru_archive_metadata(const struct zimru_archive_t *arc,
                                      const char *name,
                                      uintptr_t *out_len,
                                      struct zimru_error_t **err);

/**
 * On-disk byte length of the archive (the mmapped extent).
 */
 uint64_t zimru_archive_filesize(const struct zimru_archive_t *arc);

/**
 * Number of "article" entries — non-redirect content-namespace items
 * whose mimetype starts with `text/html`. Result is cached after the
 * first call (one O(N) walk over the content namespace). Returns 0
 * with `*err` set on read error.
 */

uint64_t zimru_archive_article_count(const struct zimru_archive_t *arc,
                                     struct zimru_error_t **err);

/**
 * Number of "media" entries — non-redirect content-namespace items
 * that are NOT articles. Result shares the cache with
 * [`zimru_archive_article_count`].
 */
 uint64_t zimru_archive_media_count(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Pick a pseudo-random entry from the content namespace. Suitable for
 * "random article" UI links; not for cryptographic use.
 */

struct zimru_entry_t *zimru_archive_random_entry(const struct zimru_archive_t *arc,
                                                 struct zimru_error_t **err);

/**
 * Number of metadata keys in the archive. O(log n) — counts the
 * `M`-namespace range without scanning or allocating the key list.
 */
 uintptr_t zimru_archive_metadata_keys_count(const struct zimru_archive_t *arc);

/**
 * Borrowed pointer to the i'th metadata key as a NUL-terminated string.
 * Lifetime tied to `arc`. Returns NULL if `idx` is out of range.
 *
 * The key list is computed once on first call and cached on the
 * archive handle, so enumerating k keys costs one metadata-range walk
 * total instead of one per call.
 */
 const char *zimru_archive_metadata_key(const struct zimru_archive_t *arc, uintptr_t idx);

/**
 * Free a `zimru_blob_t` previously returned by `zimru_item_get_data`.
 */
 void zimru_blob_free(struct zimru_blob_t *b);

/**
 * Pointer to the blob's bytes. Not NUL-terminated; lifetime tied to
 * the blob handle.
 */
 const uint8_t *zimru_blob_data(const struct zimru_blob_t *b);

/**
 * Number of bytes in the blob.
 */
 uintptr_t zimru_blob_size(const struct zimru_blob_t *b);

/**
 * Allocate a new creator with default settings (Zstd level 3, 2 MiB
 * cluster target, time-and-pid-seeded UUID). Always succeeds.
 */
 struct zimru_creator_t *zimru_creator_new(void);

/**
 * Free a creator. Safe to call on NULL. Discards any still-buffered
 * work if the creator was never finalized.
 */
 void zimru_creator_free(struct zimru_creator_t *c);

/**
 * Set the cluster compression algorithm by ZIM info-byte ID:
 *
 * * `1` — uncompressed (`Compression::None`)
 * * `4` — xz / lzma2 (`Compression::Xz`)
 * * `5` — zstd, the default (`Compression::Zstd`)
 *
 * Other IDs return `false` with `*err` set to
 * [`zimru_error_code::UnsupportedCompression`].
 */

bool zimru_creator_set_compression(struct zimru_creator_t *c,
                                   uint8_t compression_id,
                                   struct zimru_error_t **err);

/**
 * Set the compression level for the active algorithm. Range and meaning
 * are algorithm-specific:
 *
 * * Zstd — `1..=22` (negative "fast" levels also accepted by libzstd).
 *   Default `3`.
 * * Xz — `0..=9`. Default `3`.
 * * None — ignored.
 */

bool zimru_creator_set_compression_level(struct zimru_creator_t *c,
                                         int32_t level,
                                         struct zimru_error_t **err);

/**
 * Set the per-cluster decompressed-payload byte target. The bin-packer
 * closes the current cluster once its accumulated payload would exceed
 * this. Default 2 MiB matches `zimwriterfs` / `zimrecreate`.
 */

bool zimru_creator_set_cluster_size_target(struct zimru_creator_t *c,
                                           uintptr_t bytes,
                                           struct zimru_error_t **err);

/**
 * Set the archive UUID. `uuid` must point to 16 readable bytes; the
 * bytes are copied (caller retains ownership).
 */

bool zimru_creator_set_uuid(struct zimru_creator_t *c,
                            const uint8_t *uuid,
                            struct zimru_error_t **err);

/**
 * Declare the archive's main page. A `W/mainPage` redirect to
 * `C/<main_path>` is written at finalize time, matching how libzim
 * readers locate the main page.
 */

bool zimru_creator_set_main_path(struct zimru_creator_t *c,
                                 const char *main_path,
                                 struct zimru_error_t **err);

/**
 * Add a content-namespace item (stored at `C/<path>`). `content` /
 * `content_len` is copied — the caller retains ownership of the input
 * buffer. Empty payloads (`content_len == 0`) are permitted.
 *
 * Duplicate paths are not detected here; the duplicate surfaces as a
 * dirent-order failure at finalize time.
 *
 * **Namespace-prefix shortcut.** A `path` of the form `"X/<rest>"`
 * (with non-empty `<rest>`) is routed to the `X` namespace with the
 * dirent URL set to `<rest>`. This is the surface the libzim-shim's
 * fulltext-index emission uses — `"X/fulltext/xapian"` becomes
 * `{ns:'X', url:"fulltext/xapian"}` so reader-side
 * `xapian_loader.cpp` finds it. Other namespaces (M, W, Z, …) are
 * **not** peeled here; use [`zimru_creator_add_item_in_namespace`]
 * for those.
 */

bool zimru_creator_add_item(struct zimru_creator_t *c,
                            const char *path,
                            const char *title,
                            const char *mimetype,
                            const uint8_t *content,
                            uintptr_t content_len,
                            struct zimru_error_t **err);

/**
 * Add an item under an explicit namespace. `namespace` is the
 * single-byte ZIM namespace identifier (`'C'`, `'M'`, `'W'`, `'X'`,
 * `'Z'`, …); `url` is used verbatim as the dirent URL — no prefix
 * peeling. Use this when the caller already knows the target
 * namespace and wants to bypass [`zimru_creator_add_item`]'s
 * `"X/<rest>"` shortcut (or needs to write into a namespace other
 * than `C` or `X`).
 *
 * Routing semantics:
 *
 * * `'C'` (`0x43`) — same as [`zimru_creator_add_item`] without a
 *   prefix. The default content namespace.
 * * `'M'` (`0x4D`) — metadata. [`zimru_creator_add_metadata`] is the
 *   normal entry point but explicit-namespace works for callers that
 *   need a non-default mimetype outside the metadata pipeline.
 * * `'X'` (`0x58`) — fulltext / title indexes (`X/fulltext/xapian`,
 *   `X/title/xapian`). The libzim-shim writer uses this on
 *   `finishZimCreation` after compacting its in-memory Glass DB.
 * * Other namespaces — accepted; the writer emits the dirent under
 *   the requested namespace without further validation.
 */

bool zimru_creator_add_item_in_namespace(struct zimru_creator_t *c,
                                         uint8_t namespace_,
                                         const char *url,
                                         const char *title,
                                         const char *mimetype,
                                         const uint8_t *content,
                                         uintptr_t content_len,
                                         struct zimru_error_t **err);

/**
 * Add a metadata entry under `M/<name>`. `mimetype` is recorded
 * verbatim in the dirent — typical values are
 * `text/plain;charset=utf-8` (Title, Language, Description, …) and
 * `image/png` (favicons on legacy archives).
 */

bool zimru_creator_add_metadata(struct zimru_creator_t *c,
                                const char *name,
                                const char *mimetype,
                                const uint8_t *content,
                                uintptr_t content_len,
                                struct zimru_error_t **err);

/**
 * Add a square illustration of `side` pixels, stored at
 * `M/Illustration_<side>x<side>@1`. `png` / `png_len` is copied — the
 * caller retains ownership.
 */

bool zimru_creator_add_illustration(struct zimru_creator_t *c,
                                    uint32_t side,
                                    const uint8_t *png,
                                    uintptr_t png_len,
                                    struct zimru_error_t **err);

/**
 * Add a content-namespace redirect: `C/<path>` → `C/<target_path>`.
 * The target is resolved at finalize time; an unresolved target is a
 * hard failure of `zimru_creator_write_to`.
 */

bool zimru_creator_add_redirection(struct zimru_creator_t *c,
                                   const char *path,
                                   const char *title,
                                   const char *target_path,
                                   struct zimru_error_t **err);

/**
 * Add an alias entry. zimru does not yet implement true aliases (which
 * would be a type-preserving copy of the target dirent under a new
 * path/title); the implementation currently produces a redirect, which
 * downstream readers handle gracefully. Callers that *require* alias
 * semantics should test for a follow-up zimru release before relying
 * on this.
 */

bool zimru_creator_add_alias(struct zimru_creator_t *c,
                             const char *path,
                             const char *title,
                             const char *target_path,
                             struct zimru_error_t **err);

/**
 * Materialize the archive at `path`. Consumes the buffered work — on
 * success the only legal next call is `zimru_creator_free`. On failure
 * `*err` is set; the creator's inner state has still been consumed
 * (the partially-written file at `path` should be deleted by the
 * caller if it exists).
 */

bool zimru_creator_write_to(struct zimru_creator_t *c,
                            const char *path,
                            struct zimru_error_t **err);

/**
 * Open `path` for streaming output and switch the creator to
 * streaming mode. After this call returns true, every
 * `add_item` / `add_metadata` / `add_redirection` /
 * `add_illustration` call bin-packs the content into the in-flight
 * cluster and stream-encodes-and-writes to disk as the cluster
 * fills, dropping the source bytes immediately. Peak RSS is
 * bounded by `cluster_size_target × thread_count` plus the small
 * per-item dirent metadata, regardless of the total archive size.
 *
 * Any work already added via the buffered path before this call
 * is drained into the stream here.
 *
 * After `start_writing` succeeds, call `add_*` and friends as
 * usual, then call [`zimru_creator_finish_writing`] (NOT
 * `write_to`) to produce the final archive.
 *
 * Errors:
 *
 * * `path` is unreadable as UTF-8 → `*err` set, returns `false`.
 * * Output file can't be created → `*err` set, returns `false`.
 * * Already in streaming mode → `*err` set, returns `false`.
 */

bool zimru_creator_start_writing(struct zimru_creator_t *c,
                                 const char *path,
                                 struct zimru_error_t **err);

/**
 * Finalize a streaming-mode creator: encode the last cluster,
 * write the URL / title / cluster pointer tables and the dirent
 * region, fill the mime list at offset 80, write the final
 * header, append the MD5 trailer. Consumes the creator on
 * success.
 *
 * Errors:
 *
 * * Creator was never started via `start_writing` → `*err` set,
 *   returns `false`. The creator handle remains valid; caller can
 *   either `start_writing` it now or `free` it.
 * * Mid-finalize I/O failure or unresolved redirect → `*err` set,
 *   returns `false`. Inner creator is consumed; only legal next
 *   call is `free`.
 */
 bool zimru_creator_finish_writing(struct zimru_creator_t *c, struct zimru_error_t **err);

/**
 * Begin a chunked item — the caller will follow up with one or
 * more [`zimru_creator_item_chunk`] calls and a single
 * [`zimru_creator_end_item`] call to finalise. Useful for callers
 * with streaming content sources (e.g. libzim's
 * `ContentProvider::feed()`) that want to avoid slurping the
 * entire body into one buffer before handing it to zimru.
 *
 * `path` honours the same `X/<rest>` namespace-prefix shortcut as
 * [`zimru_creator_add_item`]; pass `'X'` (or any single-byte
 * namespace) explicitly via `namespace` to bypass the prefix logic.
 * Pass `0` for `namespace` to use the default routing
 * (`X/...` peel, otherwise `'C'`).
 *
 * `size_hint` is a non-binding capacity hint used to pre-allocate
 * the in-flight buffer. Pass `0` to skip.
 *
 * Errors:
 *
 * * Creator not in streaming mode → `*err` set, returns `false`.
 *   Call `start_writing` first.
 * * Another chunked item is already in flight → `*err` set,
 *   returns `false`. Call `end_item` (or `cancel_item` — TODO if
 *   needed) before starting a new one.
 */

bool zimru_creator_begin_item(struct zimru_creator_t *c,
                              uint8_t namespace_,
                              const char *path,
                              const char *title,
                              const char *mimetype,
                              uintptr_t size_hint,
                              struct zimru_error_t **err);

/**
 * Append a chunk of body bytes to the in-flight chunked item.
 * Cheap — copies `len` bytes into the in-flight buffer. Empty
 * chunks (`len == 0`, `chunk` may be NULL) are no-ops.
 *
 * Errors:
 *
 * * No item in flight → `*err` set, returns `false`. Call
 *   `begin_item` first.
 */

bool zimru_creator_item_chunk(struct zimru_creator_t *c,
                              const uint8_t *chunk,
                              uintptr_t len,
                              struct zimru_error_t **err);

/**
 * Finalise the in-flight chunked item — pushes it through the
 * streaming bin-packer (same path as `add_item`). After this
 * returns successfully, no item is in flight; the caller can
 * `begin_item` again or proceed to `finish_writing`.
 *
 * Errors:
 *
 * * No item in flight → `*err` set, returns `false`.
 * * Internal write/encode error during the (potentially
 *   triggered) cluster flush → `*err` set, returns `false`.
 */
 bool zimru_creator_end_item(struct zimru_creator_t *c, struct zimru_error_t **err);

/**
 * Free a `zimru_entry_t` previously returned by an Archive lookup.
 */
 void zimru_entry_free(struct zimru_entry_t *e);

/**
 * NUL-terminated path (e.g. "index.html"). Lifetime tied to the entry.
 */
 const char *zimru_entry_path(const struct zimru_entry_t *e);

/**
 * NUL-terminated title. Lifetime tied to the entry.
 */
 const char *zimru_entry_title(const struct zimru_entry_t *e);

/**
 * Single-byte namespace (`'C'`, `'M'`, `'W'`, `'X'`, `'A'`).
 */
 uint8_t zimru_entry_namespace(const struct zimru_entry_t *e);

/**
 * URL-pointer index of the entry.
 */
 uint32_t zimru_entry_index(const struct zimru_entry_t *e);

/**
 * True iff this entry is a redirect.
 */
 bool zimru_entry_is_redirect(const struct zimru_entry_t *e);

/**
 * Resolve an entry to an Item. If `follow` is true and the entry is a
 * redirect, the chain is followed; if false, calling on a redirect
 * returns `NotAnItem`.
 */

struct zimru_item_t *zimru_entry_get_item(const struct zimru_entry_t *e,
                                          bool follow,
                                          struct zimru_error_t **err);

/**
 * For a redirect entry, return the (one-hop) target entry.
 */

struct zimru_entry_t *zimru_entry_get_redirect_entry(const struct zimru_entry_t *e,
                                                     struct zimru_error_t **err);

/**
 * Get the human-readable message of a `zimru_error_t`. Pointer remains
 * valid until the error is freed.
 */
 const char *zimru_error_message(const struct zimru_error_t *err);

/**
 * Numeric error code (see `zimru_error_code` enum).
 */
 int32_t zimru_error_code(const struct zimru_error_t *err);

/**
 * Free a `zimru_error_t` allocated by a previous fallible call.
 */
 void zimru_error_free(struct zimru_error_t *err);

/**
 * Free a `zimru_item_t`.
 */
 void zimru_item_free(struct zimru_item_t *it);

/**
 * NUL-terminated path. Lifetime tied to the item.
 */
 const char *zimru_item_path(const struct zimru_item_t *it);

/**
 * NUL-terminated MIME type. Lifetime tied to the item.
 */
 const char *zimru_item_mimetype(const struct zimru_item_t *it);

/**
 * Single-byte namespace of the resolved entry this item belongs to
 * (e.g. `'C'`, `'A'`, `'I'`). On items obtained via redirect-following
 * lookups this is the redirect *target's* namespace, which may differ
 * from the source entry's namespace on legacy cross-namespace
 * redirects. Returns `0` on a NULL item.
 */
 uint8_t zimru_item_namespace(const struct zimru_item_t *it);

/**
 * Cluster index this item's bytes live in. Combine with
 * [`zimru_archive_cluster_offset`] to find where the cluster starts
 * in the file, or with [`zimru_item_blob_index`] +
 * [`zimru_item_direct_access`] to address the blob within the
 * cluster. Returns `0` on a NULL item — callers that care must not
 * call this without a non-NULL `it`.
 */
 uint32_t zimru_item_cluster_index(const struct zimru_item_t *it);

/**
 * Blob index within the item's cluster. Together with
 * [`zimru_item_cluster_index`] this is the `(cluster, blob)` pair
 * `zimcheck` and similar tools use to talk about an item's physical
 * position. Returns `0` on a NULL item.
 */
 uint32_t zimru_item_blob_index(const struct zimru_item_t *it);

/**
 * Decompressed size of the item's data. Returns 0 with `*err` set if
 * the cluster cannot be decoded.
 */
 uint64_t zimru_item_size(const struct zimru_item_t *it, struct zimru_error_t **err);

/**
 * Populate `out` with direct-access info for the item. Safe on a
 * NULL `it` or `out` (no-op).
 */
 void zimru_item_direct_access(const struct zimru_item_t *it, struct zimru_direct_access_t *out);

/**
 * Read the item's data as a heap-allocated blob handle. Caller frees
 * with `zimru_blob_free`.
 */

struct zimru_blob_t *zimru_item_get_data(const struct zimru_item_t *it,
                                         struct zimru_error_t **err);

/**
 * Populate `out` with a borrowed view of the item's bytes plus a pin
 * handle that keeps them alive. Returns `false` with `*err` set on
 * any failure (cluster decode error, bad blob index, NULL inputs).
 * Avoids the per-call `Box::new(zimru_blob_t)` of
 * [`zimru_item_get_data`] — costs one `Arc::clone` (refcount bump,
 * no allocation) per call. The pin must be released exactly once
 * with [`zimru_blob_view_release`].
 */

bool zimru_item_blob_view(const struct zimru_item_t *it,
                          struct zimru_blob_view_t *out,
                          struct zimru_error_t **err);

/**
 * Pre-fault the OS page cache for this item's on-disk bytes. Issues
 * `madvise(MADV_WILLNEED)` on the item's region and touches one byte
 * per 4 KB page to force synchronous fault-in. After return, every
 * page is resident; subsequent reads (including reads issued through
 * a different fd onto the same file — the OS page cache is keyed by
 * inode) hit cache instead of disk.
 *
 * Designed for the libzim-shim P7 scenario: kiwix-serve hosting a
 * multi-GB Wikipedia hands Xapian a fd at the embedded Xapian-DB
 * offset, Xapian issues eager DB-validation reads scattered across
 * the DB, and on a cold page cache the first user `/search`
 * blocks for ~12 seconds. Calling this at server start (or in a
 * background thread concurrent with other init) shifts the disk-I/O
 * cost off the first user-facing search.
 *
 * No-op on items in compressed clusters (the page-fault game only
 * makes sense for direct-access regions). Returns `false` with `*err`
 * set on a NULL item or unrecoverable lookup failure.
 */
 bool zimru_item_warmup(const struct zimru_item_t *it, struct zimru_error_t **err);

/**
 * Release the pin handle inside a [`zimru_blob_view_t`]. Safe to call
 * on a NULL `view` or a view whose `_pin` is already NULL (no-op).
 * After release the `data` and `size` fields are unchanged but
 * `data` must not be dereferenced.
 */
 void zimru_blob_view_release(struct zimru_blob_view_t *view);

/**
 * Derive a deterministic 16-byte UUID from an arbitrary byte seed.
 *
 * `seed` may be NULL only if `seed_len` is 0. `out` must point to at
 * least 16 writable bytes. The output has the high nibble of byte 6
 * set to `4` and the high two bits of byte 8 set to `10` (RFC 4122
 * v4 layout), so consumers that validate the variant won't reject it.
 */
 void zimru_uuid_generate(const uint8_t *seed, uintptr_t seed_len, uint8_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ZIMRU_H */
