/*
 * zimru — independent Rust re-implementation of the ZIM file format.
 *
 * This header is auto-generated by cbindgen from src/cffi/. Do not edit by
 * hand. Regenerate with: cargo build --release --features cffi
 *
 * Strings: returned `const char*` are NUL-terminated and remain valid until
 *   the parent handle (Entry, Item, Archive) is freed. Caller copies if a
 *   longer lifetime is needed.
 * Bytes:   returned via pointer + length; not NUL-terminated. Lifetime tied
 *   to the parent handle.
 * Errors:  fallible functions take a `zimru_error_t** err` out-parameter.
 *   On success *err is left untouched. On failure the function returns NULL
 *   (or 0/false) AND sets *err to a heap-allocated error the caller frees
 *   with zimru_error_free.
 * Ownership: anything returned via `*_t*` is owned by the caller and must
 *   be freed with the matching `*_free` function.
 */


#ifndef ZIMRU_H
#define ZIMRU_H

#pragma once

/* Generated with cbindgen:0.27.0 */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Default content namespace for "new namespace" archives.
 */
#define NS_CONTENT_NEW 67

/**
 * Metadata namespace (new-style archives).
 */
#define NS_METADATA 77

/**
 * Well-known namespace (new-style archives).
 */
#define NS_WELLKNOWN 87

/**
 * Index namespace (search indexes etc.).
 */
#define NS_INDEX 88

/**
 * Articles namespace (legacy archives).
 */
#define NS_ARTICLES_LEGACY 65

#define MIME_REDIRECT 65535

#define MIME_LINKTARGET 65534

#define MIME_DELETED 65533

#define MAGIC 72173914

#define HEADER_SIZE 80

#define NO_MAIN_PAGE UINT32_MAX

/**
 * Default target size for one cluster's worth of decompressed payload
 * (2 MiB — same as libzim's zimwriterfs default).
 */
#define DEFAULT_CLUSTER_SIZE_TARGET ((2 * 1024) * 1024)

/**
 * Opaque handle wrapping a [`crate::Archive`] plus the per-entry-string
 * cache used to give C callers stable `const char*` pointers.
 */
typedef struct zimru_archive_t zimru_archive_t;

/**
 * Opaque blob handle wrapping a [`crate::Blob`]. Holds the underlying
 * `Arc<[u8]>` cluster slice alive so the borrowed pointer returned by
 * `zimru_blob_data` stays valid until the blob is freed.
 */
typedef struct zimru_blob_t zimru_blob_t;

/**
 * Opaque writer handle. Empty placeholder for now.
 */
typedef struct zimru_creator_t zimru_creator_t;

/**
 * Opaque entry handle. Holds a Rust `Entry` plus owned `CString`s for
 * `path` and `title` so the C-side `const char*` returned by
 * `zimru_entry_path` / `zimru_entry_title` are stable for the entry's
 * lifetime.
 */
typedef struct zimru_entry_t zimru_entry_t;

/**
 * Opaque error type returned by every fallible C API entry point.
 * Intentionally NOT `#[repr(C)]` so cbindgen forward-declares it as an
 * opaque struct in the generated header (callers can only hold a
 * `zimru_error_t*`, never inspect the layout).
 */
typedef struct zimru_error_t zimru_error_t;

/**
 * Opaque item handle. Holds a Rust `Item` plus owned `CString`s for
 * `path` and `mimetype` so the C-side `const char*` returned by the
 * accessors stays valid for the item's lifetime.
 */
typedef struct zimru_item_t zimru_item_t;

/**
 * Direct-access info for an item. POD struct populated by
 * [`zimru_item_direct_access`]; mirrors [`crate::DirectAccess`].
 *
 * When `is_direct` is `true`, callers can `pread()` or `mmap()` the
 * item's bytes directly from the on-disk ZIM file at `file_offset`
 * for `size` bytes — no decompression, no copy. The standard ZIM
 * convention is to store fulltext / suggestion / Xapian indexes in
 * uncompressed clusters precisely so consumers can hand `libxapian`
 * an `int fd` + `lseek` instead of materialising the database in
 * memory or in a temp file.
 *
 * When `is_direct` is `false`, the item lives in a compressed
 * cluster; fall back to [`zimru_item_get_data`] for normal access.
 */
typedef struct zimru_direct_access_t {
  bool is_direct;
  uint64_t file_offset;
  uint64_t size;
} zimru_direct_access_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open the archive at `path` (UTF-8, NUL-terminated). Returns NULL on
 * failure and sets `*err`.
 */
 struct zimru_archive_t *zimru_archive_open(const char *path, struct zimru_error_t **err);

/**
 * Close and free a `zimru_archive_t` previously returned by
 * `zimru_archive_open`.
 */
 void zimru_archive_close(struct zimru_archive_t *arc);

/**
 * Total number of dirents (articles + redirects).
 */
 uint32_t zimru_archive_entry_count(const struct zimru_archive_t *arc);

/**
 * Same as `zimru_archive_entry_count`, included for parity with libzim's
 * `getAllEntryCount`.
 */
 uint32_t zimru_archive_all_entry_count(const struct zimru_archive_t *arc);

/**
 * Number of clusters in the archive.
 */
 uint32_t zimru_archive_cluster_count(const struct zimru_archive_t *arc);

/**
 * Copy the archive's 16-byte UUID into `out`. `out` must point to at
 * least 16 writable bytes.
 */
 void zimru_archive_uuid(const struct zimru_archive_t *arc, uint8_t *out);

/**
 * True iff the archive has a main entry pointer in its header.
 */
 bool zimru_archive_has_main_entry(const struct zimru_archive_t *arc);

/**
 * True iff the archive carries a trailing MD5 checksum.
 */
 bool zimru_archive_has_checksum(const struct zimru_archive_t *arc);

/**
 * Verify the trailing MD5 checksum. Returns true on match, false on
 * mismatch, and false-with-`*err`-set on failure to even compute it.
 */
 bool zimru_archive_check(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Look up an entry by its full namespaced path (e.g. `"C/index.html"`).
 * Returns NULL with `*err` set if not found.
 */

struct zimru_entry_t *zimru_archive_get_entry_by_path(const struct zimru_archive_t *arc,
                                                      const char *path,
                                                      struct zimru_error_t **err);

/**
 * True iff an entry with this path exists. Equivalent to
 * `zimru_archive_get_entry_by_path` returning non-NULL, without the
 * allocation.
 */
 bool zimru_archive_has_entry_by_path(const struct zimru_archive_t *arc, const char *path);

/**
 * Look up an entry by namespace + URL within that namespace
 * (e.g. ns=`'X'`, url=`"fulltext/xapian"`). This is the primitive
 * downstream callers need to reach the X / M / W namespaces on
 * new-scheme archives — `zimru_archive_get_entry_by_path` only looks
 * in the content namespace by design.
 *
 * Returns NULL with `*err` set if not found.
 */

struct zimru_entry_t *zimru_archive_get_entry_by_ns_path(const struct zimru_archive_t *arc,
                                                         uint8_t ns,
                                                         const char *url,
                                                         struct zimru_error_t **err);

/**
 * Look up an entry by its URL-pointer index (path order). Index range
 * is `[0, all_entry_count)`.
 */

struct zimru_entry_t *zimru_archive_entry_by_url_index(const struct zimru_archive_t *arc,
                                                       uint32_t idx,
                                                       struct zimru_error_t **err);

/**
 * Look up an entry by its title-pointer index (title order). On modern
 * archives this only covers the content namespace; index range is
 * `[0, zimru_archive_title_count)`.
 */

struct zimru_entry_t *zimru_archive_entry_by_title_index(const struct zimru_archive_t *arc,
                                                         uint32_t idx,
                                                         struct zimru_error_t **err);

/**
 * Number of entries in the title-order listing. On modern archives
 * this is the count of content-namespace entries only.
 */
 uint32_t zimru_archive_title_count(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Look up an entry by title in the content namespace. Returns NULL
 * with `*err` set if not found.
 */

struct zimru_entry_t *zimru_archive_get_entry_by_title(const struct zimru_archive_t *arc,
                                                       const char *title,
                                                       struct zimru_error_t **err);

/**
 * True iff this archive uses the modern single-character namespace
 * scheme (content under `C/`, metadata under `M/`, indexes under
 * `X/`, well-known under `W/`). Old archives put articles in `A/`.
 */
 bool zimru_archive_uses_new_namespaces(const struct zimru_archive_t *arc);

/**
 * Write the archive's trailing-MD5 checksum into `out` as a 32-byte
 * lowercase hex string (no NUL terminator, no hyphens). Returns
 * `false` with `*err` set if the archive has no checksum or the read
 * fails. `out` must point to at least 32 writable bytes.
 */

bool zimru_archive_checksum_hex(const struct zimru_archive_t *arc,
                                char *out,
                                struct zimru_error_t **err);

/**
 * Look up the archive's main entry. Returns NULL with `*err` set if the
 * archive has no main page.
 */

struct zimru_entry_t *zimru_archive_main_entry(const struct zimru_archive_t *arc,
                                               struct zimru_error_t **err);

/**
 * Read a metadata value as raw bytes. Writes the byte count to `out_len`
 * and returns a borrowed pointer (lifetime tied to `arc`).
 *
 * Returns NULL with `*err` set if the metadata key isn't present.
 */

const uint8_t *zimru_archive_metadata(const struct zimru_archive_t *arc,
                                      const char *name,
                                      uintptr_t *out_len,
                                      struct zimru_error_t **err);

/**
 * On-disk byte length of the archive (the mmapped extent).
 */
 uint64_t zimru_archive_filesize(const struct zimru_archive_t *arc);

/**
 * Number of "article" entries — non-redirect content-namespace items
 * whose mimetype starts with `text/html`. Result is cached after the
 * first call (one O(N) walk over the content namespace). Returns 0
 * with `*err` set on read error.
 */

uint64_t zimru_archive_article_count(const struct zimru_archive_t *arc,
                                     struct zimru_error_t **err);

/**
 * Number of "media" entries — non-redirect content-namespace items
 * that are NOT articles. Result shares the cache with
 * [`zimru_archive_article_count`].
 */
 uint64_t zimru_archive_media_count(const struct zimru_archive_t *arc, struct zimru_error_t **err);

/**
 * Pick a pseudo-random entry from the content namespace. Suitable for
 * "random article" UI links; not for cryptographic use.
 */

struct zimru_entry_t *zimru_archive_random_entry(const struct zimru_archive_t *arc,
                                                 struct zimru_error_t **err);

/**
 * Number of metadata keys in the archive.
 */
 uintptr_t zimru_archive_metadata_keys_count(const struct zimru_archive_t *arc);

/**
 * Borrowed pointer to the i'th metadata key as a NUL-terminated string.
 * Lifetime tied to `arc`. Returns NULL if `idx` is out of range.
 */
 const char *zimru_archive_metadata_key(const struct zimru_archive_t *arc, uintptr_t idx);

/**
 * Free a `zimru_blob_t` previously returned by `zimru_item_get_data`.
 */
 void zimru_blob_free(struct zimru_blob_t *b);

/**
 * Pointer to the blob's bytes. Not NUL-terminated; lifetime tied to
 * the blob handle.
 */
 const uint8_t *zimru_blob_data(const struct zimru_blob_t *b);

/**
 * Number of bytes in the blob.
 */
 uintptr_t zimru_blob_size(const struct zimru_blob_t *b);

/**
 * Allocate a new creator. Currently always succeeds; the writer C ABI
 * is otherwise unimplemented (see follow-up to issue #7).
 */
 struct zimru_creator_t *zimru_creator_new(void);

/**
 * Free a creator. Safe to call on NULL.
 */
 void zimru_creator_free(struct zimru_creator_t *c);

/**
 * Placeholder for `Creator::write_to` — currently always errors out.
 * Real implementation lands with the rest of the writer C ABI.
 */

bool zimru_creator_write_to(struct zimru_creator_t *_c,
                            const char *_path,
                            struct zimru_error_t **err);

/**
 * Free a `zimru_entry_t` previously returned by an Archive lookup.
 */
 void zimru_entry_free(struct zimru_entry_t *e);

/**
 * NUL-terminated path (e.g. "index.html"). Lifetime tied to the entry.
 */
 const char *zimru_entry_path(const struct zimru_entry_t *e);

/**
 * NUL-terminated title. Lifetime tied to the entry.
 */
 const char *zimru_entry_title(const struct zimru_entry_t *e);

/**
 * Single-byte namespace (`'C'`, `'M'`, `'W'`, `'X'`, `'A'`).
 */
 uint8_t zimru_entry_namespace(const struct zimru_entry_t *e);

/**
 * URL-pointer index of the entry.
 */
 uint32_t zimru_entry_index(const struct zimru_entry_t *e);

/**
 * True iff this entry is a redirect.
 */
 bool zimru_entry_is_redirect(const struct zimru_entry_t *e);

/**
 * Resolve an entry to an Item. If `follow` is true and the entry is a
 * redirect, the chain is followed; if false, calling on a redirect
 * returns `NotAnItem`.
 */

struct zimru_item_t *zimru_entry_get_item(const struct zimru_entry_t *e,
                                          bool follow,
                                          struct zimru_error_t **err);

/**
 * For a redirect entry, return the (one-hop) target entry.
 */

struct zimru_entry_t *zimru_entry_get_redirect_entry(const struct zimru_entry_t *e,
                                                     struct zimru_error_t **err);

/**
 * Get the human-readable message of a `zimru_error_t`. Pointer remains
 * valid until the error is freed.
 */
 const char *zimru_error_message(const struct zimru_error_t *err);

/**
 * Numeric error code (see `zimru_error_code` enum).
 */
 int32_t zimru_error_code(const struct zimru_error_t *err);

/**
 * Free a `zimru_error_t` allocated by a previous fallible call.
 */
 void zimru_error_free(struct zimru_error_t *err);

/**
 * Free a `zimru_item_t`.
 */
 void zimru_item_free(struct zimru_item_t *it);

/**
 * NUL-terminated path. Lifetime tied to the item.
 */
 const char *zimru_item_path(const struct zimru_item_t *it);

/**
 * NUL-terminated MIME type. Lifetime tied to the item.
 */
 const char *zimru_item_mimetype(const struct zimru_item_t *it);

/**
 * Decompressed size of the item's data. Returns 0 with `*err` set if
 * the cluster cannot be decoded.
 */
 uint64_t zimru_item_size(const struct zimru_item_t *it, struct zimru_error_t **err);

/**
 * Populate `out` with direct-access info for the item. Safe on a
 * NULL `it` or `out` (no-op).
 */
 void zimru_item_direct_access(const struct zimru_item_t *it, struct zimru_direct_access_t *out);

/**
 * Read the item's data as a heap-allocated blob handle. Caller frees
 * with `zimru_blob_free`.
 */

struct zimru_blob_t *zimru_item_get_data(const struct zimru_item_t *it,
                                         struct zimru_error_t **err);

/**
 * Derive a deterministic 16-byte UUID from an arbitrary byte seed.
 *
 * `seed` may be NULL only if `seed_len` is 0. `out` must point to at
 * least 16 writable bytes. The output has the high nibble of byte 6
 * set to `4` and the high two bits of byte 8 set to `10` (RFC 4122
 * v4 layout), so consumers that validate the variant won't reject it.
 */
 void zimru_uuid_generate(const uint8_t *seed, uintptr_t seed_len, uint8_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ZIMRU_H */
